// Mocks generated by Mockito from annotations
// in fintrack/test/features/budgets/domain/use_case/watch_all_budget_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:fintrack/core/database/app_database.dart' as _i4;
import 'package:fintrack/features/budgets/domain/models/available_category_with_spending.dart'
    as _i6;
import 'package:fintrack/features/budgets/domain/models/budget_model.dart'
    as _i5;
import 'package:fintrack/features/budgets/domain/repository/budgets_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BudgetsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetsRepository extends _i1.Mock implements _i2.BudgetsRepository {
  MockBudgetsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> insertBudget(_i4.BudgetsTableCompanion? budget) =>
      (super.noSuchMethod(
        Invocation.method(#insertBudget, [budget]),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Stream<List<_i5.BudgetWithSpending>> watchAll() => (super.noSuchMethod(
    Invocation.method(#watchAll, []),
    returnValue: _i3.Stream<List<_i5.BudgetWithSpending>>.empty(),
  ) as _i3.Stream<List<_i5.BudgetWithSpending>>);

  @override
  _i3.Stream<List<_i6.AvailableCategoryWithSpending>>
  getAvailableCategories() => (super.noSuchMethod(
    Invocation.method(#getAvailableCategories, []),
    returnValue: _i3.Stream<List<_i6.AvailableCategoryWithSpending>>.empty(),
  ) as _i3.Stream<List<_i6.AvailableCategoryWithSpending>>);
}
