// Mocks generated by Mockito from annotations
// in fintrack/test/features/accounts/presentaion/state_manege/accounts_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fintrack/features/accounts/domain/models/wallet_model.dart'
    as _i5;
import 'package:fintrack/features/accounts/domain/repository/wellets_repository.dart'
    as _i2;
import 'package:fintrack/features/accounts/domain/use_case/insert_wallet_use_case.dart'
    as _i3;
import 'package:fintrack/features/accounts/domain/use_case/watch_wallets_use_case.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWelletsRepository_0 extends _i1.SmartFake
    implements _i2.WelletsRepository {
  _FakeWelletsRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InsertWalletUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockInsertWalletUseCase extends _i1.Mock
    implements _i3.InsertWalletUseCase {
  MockInsertWalletUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WelletsRepository get welletsRepository => (super.noSuchMethod(
    Invocation.getter(#welletsRepository),
    returnValue: _FakeWelletsRepository_0(
      this,
      Invocation.getter(#welletsRepository),
    ),
  ) as _i2.WelletsRepository);

  @override
  _i4.Future<int> insertWallet(_i5.WalletModel? wallet) => (super.noSuchMethod(
    Invocation.method(#insertWallet, [wallet]),
    returnValue: _i4.Future<int>.value(0),
  ) as _i4.Future<int>);
}

/// A class which mocks [WatchWalletsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchWalletsUseCase extends _i1.Mock
    implements _i6.WatchWalletsUseCase {
  MockWatchWalletsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WelletsRepository get welletsRepository => (super.noSuchMethod(
    Invocation.getter(#welletsRepository),
    returnValue: _FakeWelletsRepository_0(
      this,
      Invocation.getter(#welletsRepository),
    ),
  ) as _i2.WelletsRepository);

  @override
  _i4.Stream<List<_i5.WalletModel>> watchWallet() => (super.noSuchMethod(
    Invocation.method(#watchWallet, []),
    returnValue: _i4.Stream<List<_i5.WalletModel>>.empty(),
  ) as _i4.Stream<List<_i5.WalletModel>>);
}
