// Mocks generated by Mockito from annotations
// in fintrack/test/features/accounts/domain/use_case/insert_wallet_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:fintrack/features/accounts/domain/models/wallet_model.dart'
    as _i4;
import 'package:fintrack/features/accounts/domain/repository/wellets_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [WelletsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWelletsRepository extends _i1.Mock implements _i2.WelletsRepository {
  MockWelletsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> insertWallet(_i4.WalletModel? wallet) => (super.noSuchMethod(
    Invocation.method(#insertWallet, [wallet]),
    returnValue: _i3.Future<int>.value(0),
  ) as _i3.Future<int>);

  @override
  _i3.Stream<List<_i4.WalletModel>> watchWallet() => (super.noSuchMethod(
    Invocation.method(#watchWallet, []),
    returnValue: _i3.Stream<List<_i4.WalletModel>>.empty(),
  ) as _i3.Stream<List<_i4.WalletModel>>);
}
