// Mocks generated by Mockito from annotations
// in fintrack/test/core/presentaion/bloc/transacation_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:fintrack/core/database/app_database.dart' as _i5;
import 'package:fintrack/core/domain/models/transaction_with_details.dart'
    as _i8;
import 'package:fintrack/core/domain/repository/transactions_repository.dart'
    as _i2;
import 'package:fintrack/core/domain/use_case/delete_transaction_use_case.dart'
    as _i6;
import 'package:fintrack/core/domain/use_case/get_category_use_case.dart'
    as _i9;
import 'package:fintrack/core/domain/use_case/insert_transaction_use_case.dart'
    as _i3;
import 'package:fintrack/core/domain/use_case/watch_by_wallet_use_case.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTransactionsRepository_0 extends _i1.SmartFake
    implements _i2.TransactionsRepository {
  _FakeTransactionsRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InsertTransactionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockInsertTransactionUseCase extends _i1.Mock
    implements _i3.InsertTransactionUseCase {
  MockInsertTransactionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TransactionsRepository get transactionsRepository => (super.noSuchMethod(
    Invocation.getter(#transactionsRepository),
    returnValue: _FakeTransactionsRepository_0(
      this,
      Invocation.getter(#transactionsRepository),
    ),
  ) as _i2.TransactionsRepository);

  @override
  _i4.Future<int> insertTransaction(_i5.TransactionsTableCompanion? txn) =>
      (super.noSuchMethod(
        Invocation.method(#insertTransaction, [txn]),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}

/// A class which mocks [DeleteTransactionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteTransactionUseCase extends _i1.Mock
    implements _i6.DeleteTransactionUseCase {
  MockDeleteTransactionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TransactionsRepository get transactionsRepository => (super.noSuchMethod(
    Invocation.getter(#transactionsRepository),
    returnValue: _FakeTransactionsRepository_0(
      this,
      Invocation.getter(#transactionsRepository),
    ),
  ) as _i2.TransactionsRepository);

  @override
  _i4.Future<void> deleteTransaction(int? transactionId) => (super.noSuchMethod(
    Invocation.method(#deleteTransaction, [transactionId]),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);
}

/// A class which mocks [WatchByWalletUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchByWalletUseCase extends _i1.Mock
    implements _i7.WatchByWalletUseCase {
  MockWatchByWalletUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TransactionsRepository get transactionsRepository => (super.noSuchMethod(
    Invocation.getter(#transactionsRepository),
    returnValue: _FakeTransactionsRepository_0(
      this,
      Invocation.getter(#transactionsRepository),
    ),
  ) as _i2.TransactionsRepository);

  @override
  _i4.Stream<List<_i8.TransactionWithDetails>> watchByWallet(int? walletId) =>
      (super.noSuchMethod(
        Invocation.method(#watchByWallet, [walletId]),
        returnValue: _i4.Stream<List<_i8.TransactionWithDetails>>.empty(),
      ) as _i4.Stream<List<_i8.TransactionWithDetails>>);
}

/// A class which mocks [GetCategoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoryUseCase extends _i1.Mock
    implements _i9.GetCategoryUseCase {
  MockGetCategoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TransactionsRepository get transactionsRepository => (super.noSuchMethod(
    Invocation.getter(#transactionsRepository),
    returnValue: _FakeTransactionsRepository_0(
      this,
      Invocation.getter(#transactionsRepository),
    ),
  ) as _i2.TransactionsRepository);

  @override
  _i4.Future<List<_i5.CategoriesTableData>> getCategory() =>
      (super.noSuchMethod(
        Invocation.method(#getCategory, []),
        returnValue: _i4.Future<List<_i5.CategoriesTableData>>.value(
          <_i5.CategoriesTableData>[],
        ),
      ) as _i4.Future<List<_i5.CategoriesTableData>>);
}
