// Mocks generated by Mockito from annotations
// in fintrack/test/features/budgets/data/budgets_repository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i7;

import 'package:drift/backends.dart' as _i4;
import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i5;
import 'package:fintrack/core/database/app_database.dart' as _i2;
import 'package:fintrack/features/budgets/data/dao/budgets_dao.dart' as _i6;
import 'package:fintrack/features/budgets/domain/models/available_category_with_spending.dart'
    as _i10;
import 'package:fintrack/features/budgets/domain/models/budget_model.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_1 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_2 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_3 extends _i1.SmartFake implements _i4.QueryExecutor {
  _FakeQueryExecutor_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_4 extends _i1.SmartFake
    implements _i5.StreamQueryStore {
  _FakeStreamQueryStore_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_5 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CategoriesTableTable_6 extends _i1.SmartFake
    implements _i2.$CategoriesTableTable {
  _Fake$CategoriesTableTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$BudgetsTableTable_7 extends _i1.SmartFake
    implements _i2.$BudgetsTableTable {
  _Fake$BudgetsTableTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$WalletsTableTable_8 extends _i1.SmartFake
    implements _i2.$WalletsTableTable {
  _Fake$WalletsTableTable_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$TransactionsTableTable_9 extends _i1.SmartFake
    implements _i2.$TransactionsTableTable {
  _Fake$TransactionsTableTable_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBudgetsDaoManager_10 extends _i1.SmartFake
    implements _i6.BudgetsDaoManager {
  _FakeBudgetsDaoManager_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_11<T1> extends _i1.SmartFake implements _i7.Future<T1> {
  _FakeFuture_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_12<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_13<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_14<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake
    implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_15<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_16<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_17<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_18<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_19 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BudgetsDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetsDao extends _i1.Mock implements _i6.BudgetsDao {
  MockBudgetsDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get attachedDatabase => (super.noSuchMethod(
    Invocation.getter(#attachedDatabase),
    returnValue: _FakeAppDatabase_0(this, Invocation.getter(#attachedDatabase)),
  ) as _i2.AppDatabase);

  @override
  _i3.DatabaseConnection get connection => (super.noSuchMethod(
    Invocation.getter(#connection),
    returnValue: _FakeDatabaseConnection_1(
      this,
      Invocation.getter(#connection),
    ),
  ) as _i3.DatabaseConnection);

  @override
  _i3.DriftDatabaseOptions get options => (super.noSuchMethod(
    Invocation.getter(#options),
    returnValue: _FakeDriftDatabaseOptions_2(this, Invocation.getter(#options)),
  ) as _i3.DriftDatabaseOptions);

  @override
  _i3.SqlTypes get typeMapping => (super.noSuchMethod(
    Invocation.getter(#typeMapping),
    returnValue: _i8.dummyValue<_i3.SqlTypes>(
      this,
      Invocation.getter(#typeMapping),
    ),
  ) as _i3.SqlTypes);

  @override
  _i4.QueryExecutor get executor => (super.noSuchMethod(
    Invocation.getter(#executor),
    returnValue: _FakeQueryExecutor_3(this, Invocation.getter(#executor)),
  ) as _i4.QueryExecutor);

  @override
  _i5.StreamQueryStore get streamQueries => (super.noSuchMethod(
    Invocation.getter(#streamQueries),
    returnValue: _FakeStreamQueryStore_4(
      this,
      Invocation.getter(#streamQueries),
    ),
  ) as _i5.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
    Invocation.getter(#resolvedEngine),
    returnValue: _FakeDatabaseConnectionUser_5(
      this,
      Invocation.getter(#resolvedEngine),
    ),
  ) as _i3.DatabaseConnectionUser);

  @override
  _i2.$CategoriesTableTable get categoriesTable => (super.noSuchMethod(
    Invocation.getter(#categoriesTable),
    returnValue: _Fake$CategoriesTableTable_6(
      this,
      Invocation.getter(#categoriesTable),
    ),
  ) as _i2.$CategoriesTableTable);

  @override
  _i2.$BudgetsTableTable get budgetsTable => (super.noSuchMethod(
    Invocation.getter(#budgetsTable),
    returnValue: _Fake$BudgetsTableTable_7(
      this,
      Invocation.getter(#budgetsTable),
    ),
  ) as _i2.$BudgetsTableTable);

  @override
  _i2.$WalletsTableTable get walletsTable => (super.noSuchMethod(
    Invocation.getter(#walletsTable),
    returnValue: _Fake$WalletsTableTable_8(
      this,
      Invocation.getter(#walletsTable),
    ),
  ) as _i2.$WalletsTableTable);

  @override
  _i2.$TransactionsTableTable get transactionsTable => (super.noSuchMethod(
    Invocation.getter(#transactionsTable),
    returnValue: _Fake$TransactionsTableTable_9(
      this,
      Invocation.getter(#transactionsTable),
    ),
  ) as _i2.$TransactionsTableTable);

  @override
  _i6.BudgetsDaoManager get managers => (super.noSuchMethod(
    Invocation.getter(#managers),
    returnValue: _FakeBudgetsDaoManager_10(this, Invocation.getter(#managers)),
  ) as _i6.BudgetsDaoManager);

  @override
  _i7.Future<int> insertBudget(_i2.BudgetsTableCompanion? budget) =>
      (super.noSuchMethod(
        Invocation.method(#insertBudget, [budget]),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Stream<List<_i9.BudgetWithSpending>> watchAll() => (super.noSuchMethod(
    Invocation.method(#watchAll, []),
    returnValue: _i7.Stream<List<_i9.BudgetWithSpending>>.empty(),
  ) as _i7.Stream<List<_i9.BudgetWithSpending>>);

  @override
  _i7.Stream<List<_i10.AvailableCategoryWithSpending>>
  getAvailableCategories() => (super.noSuchMethod(
    Invocation.method(#getAvailableCategories, []),
    returnValue: _i7.Stream<List<_i10.AvailableCategoryWithSpending>>.empty(),
  ) as _i7.Stream<List<_i10.AvailableCategoryWithSpending>>);

  @override
  _i7.Stream<T> createStream<T extends Object>(
    _i5.QueryStreamFetcher<T>? stmt,
  ) => (super.noSuchMethod(
    Invocation.method(#createStream, [stmt]),
    returnValue: _i7.Stream<T>.empty(),
  ) as _i7.Stream<T>);

  @override
  T alias<T, D>(_i3.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
        Invocation.method(#alias, [table, alias]),
        returnValue: _i8.dummyValue<T>(
          this,
          Invocation.method(#alias, [table, alias]),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Stream<Set<_i3.TableUpdate>> tableUpdates([
    _i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any(),
  ]) => (super.noSuchMethod(
    Invocation.method(#tableUpdates, [query]),
    returnValue: _i7.Stream<Set<_i3.TableUpdate>>.empty(),
  ) as _i7.Stream<Set<_i3.TableUpdate>>);

  @override
  _i7.Future<T> doWhenOpened<T>(
    _i7.FutureOr<T> Function(_i4.QueryExecutor)? fn,
  ) => (super.noSuchMethod(
    Invocation.method(#doWhenOpened, [fn]),
    returnValue:
        _i8.ifNotNull(
          _i8.dummyValueOrNull<T>(this, Invocation.method(#doWhenOpened, [fn])),
          (T v) => _i7.Future<T>.value(v),
        ) ??
        _FakeFuture_11<T>(this, Invocation.method(#doWhenOpened, [fn])),
  ) as _i7.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) => (super.noSuchMethod(
    Invocation.method(#into, [table]),
    returnValue: _FakeInsertStatement_12<T, D>(
      this,
      Invocation.method(#into, [table]),
    ),
  ) as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
    _i3.TableInfo<Tbl, R>? table,
  ) => (super.noSuchMethod(
    Invocation.method(#update, [table]),
    returnValue: _FakeUpdateStatement_13<Tbl, R>(
      this,
      Invocation.method(#update, [table]),
    ),
  ) as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) => (super.noSuchMethod(
    Invocation.method(#select, [table], {#distinct: distinct}),
    returnValue: _FakeSimpleSelectStatement_14<T, R>(
      this,
      Invocation.method(#select, [table], {#distinct: distinct}),
    ),
  ) as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) => (super.noSuchMethod(
    Invocation.method(#selectOnly, [table], {#distinct: distinct}),
    returnValue: _FakeJoinedSelectStatement_15<T, R>(
      this,
      Invocation.method(#selectOnly, [table], {#distinct: distinct}),
    ),
  ) as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
    Iterable<_i3.Expression<Object>>? columns,
  ) => (super.noSuchMethod(
    Invocation.method(#selectExpressions, [columns]),
    returnValue: _FakeBaseSelectStatement_16<_i3.TypedResult>(
      this,
      Invocation.method(#selectExpressions, [columns]),
    ),
  ) as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) => (super.noSuchMethod(
    Invocation.method(#delete, [table]),
    returnValue: _FakeDeleteStatement_17<T, D>(
      this,
      Invocation.method(#delete, [table]),
    ),
  ) as _i3.DeleteStatement<T, D>);

  @override
  _i7.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) => (super.noSuchMethod(
    Invocation.method(
      #customUpdate,
      [query],
      {#variables: variables, #updates: updates, #updateKind: updateKind},
    ),
    returnValue: _i7.Future<int>.value(0),
  ) as _i7.Future<int>);

  @override
  _i7.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) => (super.noSuchMethod(
    Invocation.method(
      #customInsert,
      [query],
      {#variables: variables, #updates: updates},
    ),
    returnValue: _i7.Future<int>.value(0),
  ) as _i7.Future<int>);

  @override
  _i7.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) => (super.noSuchMethod(
    Invocation.method(
      #customWriteReturning,
      [query],
      {#variables: variables, #updates: updates, #updateKind: updateKind},
    ),
    returnValue: _i7.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
  ) as _i7.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) => (super.noSuchMethod(
    Invocation.method(
      #customSelect,
      [query],
      {#variables: variables, #readsFrom: readsFrom},
    ),
    returnValue: _FakeSelectable_18<_i3.QueryRow>(
      this,
      Invocation.method(
        #customSelect,
        [query],
        {#variables: variables, #readsFrom: readsFrom},
      ),
    ),
  ) as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) => (super.noSuchMethod(
    Invocation.method(
      #customSelectQuery,
      [query],
      {#variables: variables, #readsFrom: readsFrom},
    ),
    returnValue: _FakeSelectable_18<_i3.QueryRow>(
      this,
      Invocation.method(
        #customSelectQuery,
        [query],
        {#variables: variables, #readsFrom: readsFrom},
      ),
    ),
  ) as _i3.Selectable<_i3.QueryRow>);

  @override
  _i7.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
        Invocation.method(#customStatement, [statement, args]),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<T> transaction<T>(
    _i7.Future<T> Function()? action, {
    bool? requireNew = false,
  }) => (super.noSuchMethod(
    Invocation.method(#transaction, [action], {#requireNew: requireNew}),
    returnValue:
        _i8.ifNotNull(
          _i8.dummyValueOrNull<T>(
            this,
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
          ),
          (T v) => _i7.Future<T>.value(v),
        ) ??
        _FakeFuture_11<T>(
          this,
          Invocation.method(#transaction, [action], {#requireNew: requireNew}),
        ),
  ) as _i7.Future<T>);

  @override
  _i7.Future<T> exclusively<T>(_i7.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(#exclusively, [action]),
        returnValue:
            _i8.ifNotNull(
              _i8.dummyValueOrNull<T>(
                this,
                Invocation.method(#exclusively, [action]),
              ),
              (T v) => _i7.Future<T>.value(v),
            ) ??
            _FakeFuture_11<T>(this, Invocation.method(#exclusively, [action])),
      ) as _i7.Future<T>);

  @override
  _i7.Future<void> batch(_i7.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(#batch, [runInBatch]),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<T> runWithInterceptor<T>(
    _i7.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) => (super.noSuchMethod(
    Invocation.method(
      #runWithInterceptor,
      [action],
      {#interceptor: interceptor},
    ),
    returnValue:
        _i8.ifNotNull(
          _i8.dummyValueOrNull<T>(
            this,
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
          ),
          (T v) => _i7.Future<T>.value(v),
        ) ??
        _FakeFuture_11<T>(
          this,
          Invocation.method(
            #runWithInterceptor,
            [action],
            {#interceptor: interceptor},
          ),
        ),
  ) as _i7.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) => (super.noSuchMethod(
    Invocation.method(
      #$write,
      [component],
      {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
    ),
    returnValue: _FakeGenerationContext_19(
      this,
      Invocation.method(
        #$write,
        [component],
        {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
      ),
    ),
  ) as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) => (super.noSuchMethod(
    Invocation.method(
      #$writeInsertable,
      [table, insertable],
      {#startIndex: startIndex},
    ),
    returnValue: _FakeGenerationContext_19(
      this,
      Invocation.method(
        #$writeInsertable,
        [table, insertable],
        {#startIndex: startIndex},
      ),
    ),
  ) as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeUpdateInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) => (super.noSuchMethod(
    Invocation.method(
      #$writeUpdateInsertable,
      [table, insertable],
      {#startIndex: startIndex},
    ),
    returnValue: _FakeGenerationContext_19(
      this,
      Invocation.method(
        #$writeUpdateInsertable,
        [table, insertable],
        {#startIndex: startIndex},
      ),
    ),
  ) as _i3.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) => (super.noSuchMethod(
    Invocation.method(#$expandVar, [start, amount]),
    returnValue: _i8.dummyValue<String>(
      this,
      Invocation.method(#$expandVar, [start, amount]),
    ),
  ) as String);

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
    Invocation.method(#close, []),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);
}
