// Mocks generated by Mockito from annotations
// in fintrack/test/core/domain/use_case/watch_by_wallet_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:fintrack/core/database/app_database.dart' as _i4;
import 'package:fintrack/core/domain/models/transaction_with_details.dart'
    as _i5;
import 'package:fintrack/core/domain/repository/transactions_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TransactionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionsRepository extends _i1.Mock
    implements _i2.TransactionsRepository {
  MockTransactionsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> insertTransaction(_i4.TransactionsTableCompanion? txn) =>
      (super.noSuchMethod(
        Invocation.method(#insertTransaction, [txn]),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Stream<List<_i5.TransactionWithDetails>> watchByWallet(int? walletId) =>
      (super.noSuchMethod(
        Invocation.method(#watchByWallet, [walletId]),
        returnValue: _i3.Stream<List<_i5.TransactionWithDetails>>.empty(),
      ) as _i3.Stream<List<_i5.TransactionWithDetails>>);

  @override
  _i3.Future<void> deleteTransaction(int? transactionId) => (super.noSuchMethod(
    Invocation.method(#deleteTransaction, [transactionId]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.CategoriesTableData>> getCategory() =>
      (super.noSuchMethod(
        Invocation.method(#getCategory, []),
        returnValue: _i3.Future<List<_i4.CategoriesTableData>>.value(
          <_i4.CategoriesTableData>[],
        ),
      ) as _i3.Future<List<_i4.CategoriesTableData>>);
}
